export default {
    firstName: 'Francois',
    secondName: 'Vongue',
    login: 'hellatsugoi',
    email: 'hellatsugoi@gmail.com',
    password: '125125dfsf32',
    words: [
        {
            content: 'hello',
            tags: ['greeting'],
            translations: ['привет'],
            notes: 'word to greet people',
            familiar: false,
            editing: false,
        },
        {
            content: 'hey',
            tags: ['greeting'],
            translations: ['привет'],
            notes: 'word to greet people',
            familiar: true,
            editing: false,
        },
        {
            content: 'bonjour',
            tags: ['greeting'],
            translations: ['добрый день'],
            notes: 'word to greet people',
            familiar: false,
            editing: false,
        },
        {
            content: 'hello',
            tags: ['greeting'],
            translations: ['привет'],
            notes: 'word to greet people',
            familiar: false,
            editing: false,
        },
        {
            content: 'hey',
            tags: ['greeting'],
            translations: ['привет'],
            notes: 'word to greet people',
            familiar: false,
            editing: false,
        },
        {
            content: 'bonjour',
            tags: ['greeting'],
            translations: ['добрый день'],
            notes: 'word to greet people',
            familiar: false,
            editing: false,
        },
        {
            content: 'hey',
            tags: ['greeting'],
            translations: ['привет'],
            notes: 'word to greet people',
            familiar: true,
            editing: false,
        },
        {
            content: 'bonjour',
            tags: ['greeting'],
            translations: ['добрый день'],
            notes: 'word to greet people',
            familiar: false,
            editing: false,
        },
        {
            content: 'hello',
            tags: ['greeting'],
            translations: ['привет'],
            notes: 'word to greet people',
            familiar: false,
            editing: false,
        },
        {
            content: 'hey',
            tags: ['greeting'],
            translations: ['привет'],
            notes: 'word to greet people',
            familiar: false,
            editing: false,
        },
        {
            content: 'bonjour',
            tags: ['greeting'],
            translations: ['добрый день'],
            notes: 'word to greet people',
            familiar: false,
            editing: false,
        },
        {
            content: 'hey',
            tags: ['greeting'],
            translations: ['привет'],
            notes: 'word to greet people',
            familiar: true,
            editing: false,
        },
        {
            content: 'bonjour',
            tags: ['greeting'],
            translations: ['добрый день'],
            notes: 'word to greet people',
            familiar: false,
            editing: false,
        },
        {
            content: 'hello',
            tags: ['greeting'],
            translations: ['привет'],
            notes: 'word to greet people',
            familiar: false,
            editing: false,
        },
        {
            content: 'hey',
            tags: ['greeting'],
            translations: ['привет'],
            notes: 'word to greet people',
            familiar: false,
            editing: false,
        },
        {
            content: 'bonjour',
            tags: ['greeting'],
            translations: ['добрый день'],
            notes: 'word to greet people',
            familiar: false,
            editing: false,
        },
    ]
}