export default {
    firstName: 'Francois',
    secondName: 'Vongue',
    login: 'hellatsugoi',
    email: 'hellatsugoi@gmail.com',
    password: '125125dfsf32',
    words: [
        {
            id: 1,
            content: 'hello',
            tags: ['greeting'],
            translations: ['привет'],
            notes: 'word to greet people',
            familiar: false,
            editing: false,
        },
        {
            id: 2,
            content: 'hey',
            tags: ['greeting'],
            translations: ['привет'],
            notes: 'word to greet people',
            familiar: true,
            editing: false,
        },
        {
            id: 3,
            content: 'bonjour',
            tags: ['greeting'],
            translations: ['добрый день'],
            notes: 'word to greet people',
            familiar: false,
            editing: false,
        },
        {
            id: 4,
            content: 'good morning',
            tags: ['greeting'],
            translations: ['привет'],
            notes: 'word to greet people',
            familiar: false,
            editing: false,
        },
        {
            id: 5,
            content: 'good day',
            tags: ['greeting'],
            translations: ['привет'],
            notes: 'word to greet people',
            familiar: false,
            editing: false,
        },
        {
            id: 6,
            content: 'nice to see you',
            tags: ['greeting'],
            translations: ['добрый день'],
            notes: 'word to greet people',
            familiar: false,
            editing: false,
        },
        {
            id: 7,
            content: 'heeeey',
            tags: ['greeting'],
            translations: ['привет'],
            notes: 'word to greet people',
            familiar: true,
            editing: false,
        }
    ],
    info: {
        words: ['hello', 'hey', 'bonjour', 'good morning', 'good day', 'nice to see you', 'heeeey'],
        tags: ['home','work','workout','days','weeks','months'],
        topics: ['matrix','genzel und gretel','greetings','years','mr nobody']
    }
}